name: "Modpack Issue"
description: "Please report your bug"
title: "[Modpack] <Short Summary>"
labels:
  - Bug
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and detailed explanation of the issue.
      placeholder: "Please descripe your bug"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps needed to reproduce the issue
      placeholder: |
        1. Step:
        2. Step:
        3. Step:
        
        Expected behavior:
    validations:
      required: false

  

  

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Singleplayer
        - Private Server
        - Public Server
    validations:
      required: true

  - type: dropdown
    id: target_milestone
    attributes:
      label: Target Milestone
      description: Select the milestone this issue should be assigned to
      options:
        - Version pre1.4.0
        - Version pre1.3.0
        - Version pre1.2.0
        - Version pre1.1.0
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: Add screenshots, logs, or any other helpful details
      placeholder: "Optional"
    validations:
      required: false
      
